### ISSUE TITLE
xr.exception.GraphicsDeviceInvalidError

### ISSUE THREAD

**Issue by Steph-Stein** [cmbruns/pyopenxr#120]
### Discussed in https://github.com/cmbruns/pyopenxr/discussions/119

<div type='discussions-op-text'>

<sup>Originally posted by **Steph-Stein** December 15, 2024</sup>
Dear,

I succeed to build and run hello_xr from scratch with openxr official sdk.

I am trying to use pyopenxr but when i launch pink_world.py or other samples i always get this error.

"""
15/12 09:38:09.473 {DEBUG}   [OXR] xrNegotiateLoaderRuntimeInterface loading 1.1.40
Traceback (most recent call last):
  File "D:\Stéphane\Programmation\Codes_Python\Casque_VR\OpenXR\pink_world.py", line 11, in <module>
    with xr.ContextObject(
  File "C:\Users\steph\AppData\Local\Programs\Python\Python311\Lib\site-packages\xr\context_object.py", line 73, in __enter__
    self.session = create_session(
                   ^^^^^^^^^^^^^^^
  File "C:\Users\steph\AppData\Local\Programs\Python\Python311\Lib\site-packages\xr\functions.py", line 262, in create_session
    raise result
xr.exception.GraphicsDeviceInvalidError: The given graphics device is not in a valid state. The graphics device could be lost or initialized without meeting graphics requirements.
"""

I am on Windows 11 and i tried with python 8 and python 11, pyopengl and pyopengl-accelerated installed and working.

My headset is a meta quest 2 with oculus runtime.

What can i do please ?

Stephane.
</div>

**Comment by cmbruns** [comment]
Here's how I do it: Run SteamVR on the Windows machine. It might say "Awaiting wireless connection". Run "Steam Link" on your headset, and connect to your desktop. Is this similar to your setup?
